### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ex0dus-0x** [NuappsOSS/vplus-server#1]
__Short Term Goals__:

* [ ]  Logging facility implementation
* [ ] Argparsing (users supplied API tokens through arguments)
* [ ] `setup.py
* [ ] database management - better and more secure queries being made to Firebase 
* [ ] Docstrings (use my [tool](https://github.com/ex0dus-0x/surgeon))

__Long Term Goals__:

* [ ] Elastic search queries
* [ ] Better content addressing for queries
* [ ] Full DB migration (move to ORM, possibly switch Firebase to NoSQL)
